### ISSUE TITLE
MIG in a dedicated container is hardly of any use

### ISSUE THREAD

**Issue by mpurzynski** [mozmeao/mig-agent#1]
Hey!

MIG run this way, within a container, will only see:
1. processes from this container's PID namespace
2. files from this container's filesystem namespace (i.e. bare OS files + MIG files)

MIG's main purpose is to scan for artifacts, system-wide and answer questions like

a. is file /a/b/c present?
b. is process evilprocess present?

Even if it is, MIG would not be able to see it anyway.

**Comment by jgmize** [comment]
We run the containers in [privileged](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) mode with the SYS_PTRACE [capability](http://man7.org/linux/man-pages/man7/capabilities.7.html) and mount the host's root filesystem in a [hostPath volume](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath). I've copied [daemonset.yaml](https://github.com/mozmeao/mig-agent/blob/master/daemonset.yaml) from our private repo into this one for reference.

**Comment by jgmize** [comment]
Note that in the above linked daemonset.yaml we also set hostPID and hostNetwork to true, which allows the container to access the [host's process and network namespaces](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces).
